version: "3"

services:
  apiserver:
    build: 
      context: ./
    container_name: 'apiserver'
    restart: 'always'
    hostname: howmuch.localapi
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
    networks:
      - beuschernet          
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    volumes:
      - './data:/data/db'
    networks:
      - beuschernet
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_ROOT_DATABASE}
      MONGO_INITDB_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      MONGO_INITDB_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      MONGO_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb    
    networks:
      - beuschernet
networks:
  beuschernet: