version: "3"

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    volumes:
      - 'mongodata:/data/db'
    networks:
      - beuschernet
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_ROOT_DATABASE}
      MONGO_INITDB_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      MONGO_INITDB_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      MONGO_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  appclient:
    build: 
      context: ./client
    container_name: 'appclient'
    restart: 'always'
    hostname: howmuch.local
    ports:
      - "3000:3000"
    depends_on:
      - 'appserver'
    networks:
      - beuschernet    
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules            
  appserver:
    build: 
      context: ./server
    container_name: 'appserver'
    restart: 'always'
    hostname: howmuch.localapi
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
    networks:
      - beuschernet        
  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb    
    networks:
      - beuschernet
    links:
      - "mongodb:mongodb"
networks:
  beuschernet:
volumes:
  mongodata: